# Generated by Django 4.1.4 on 2022-12-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_alllisting_listingid_alter_bid_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedbid',
            name='winprice',
            field=models.IntegerField(default=0),
        ),
    ]
